copyright: Apache License v2.0
description: JFrame - a JavaScript implementation of an IFrame w/ some UI magic to boot.
name: JFrame
sources: [
  Source/JFrameFilters/JFrame.FormRequest.js,
  Source/JFrameFilters/JFrame.Clearfix.js,
  Source/JFrameFilters/JFrame.AutoRefresh.js,
  Source/JFrameFilters/JFrame.DoubleClickDelegate.js,
  Source/JFrameFilters/JFrame.ToggleHistory.js,
  Source/JFrameRenderers/JFrame.Alert.js,
  Source/JFrameRenderers/JFrame.Prompt.js,
  Source/JFrameRenderers/JFrame.PartialRefresh.js,
  Source/JFrameRenderers/PartialUpdate.js,
  Source/JFrame/JFrame.Browser.js,
  Source/JFrame/JFrame.Container.js,
  Source/JFrame/JFrame.Error.js,
  Source/JFrame/JFrame.js,
  Source/JFrame/JFrame.Keys.js,
  Source/JFrame/JFrame.Request.js,
  Source/JFrame/JFrame.Window.js,
  Source/JFrame/MooTools.Config.js,
  Source/JFrameLinkers/JFrame.AjaxLoad.js,
  Source/JFrameLinkers/JFrame.CheckAllOrNone.js,
  Source/JFrameLinkers/JFrame.ConfirmAndPost.js,
  Source/JFrameLinkers/JFrame.FakeRefresh.js,
  Source/JFrameLinkers/JFrame.HideParent.js,
  Source/JFrameLinkers/JFrame.LivePath.js,
  Source/JFrameLinkers/JFrame.Nav.js,
  Source/JFrameLinkers/JFrame.NoScroll.js,
  Source/JFrameLinkers/JFrame.PromptAndPost.js,
  Source/JFrameLinkers/JFrame.Refresh.js,
  Source/JFrameLinkers/JFrame.RefreshWithParams.js,
  Source/JFrameLinkers/JFrame.SplitViewLinkers.js,
  Source/JFrameLinkers/JFrame.SubmitLink.js,
  Source/BehaviorFilters/Behavior.Autocomplete.js,
  Source/BehaviorFilters/Behavior.CollapsingElements.js,
  Source/BehaviorFilters/Behavior.ContextMenu.js,
  Source/BehaviorFilters/Behavior.DataGroupToggle.js,
  Source/BehaviorFilters/Behavior.FilterInput.js,
  Source/BehaviorFilters/Behavior.FitText.js,
  Source/BehaviorFilters/Behavior.FlashMessage.js,
  Source/BehaviorFilters/Behavior.FormValidatorScroller.js,
  Source/BehaviorFilters/Behavior.HtmlTableCheckSelected.js,
  Source/BehaviorFilters/Behavior.HtmlTableChromeHack.js,
  Source/BehaviorFilters/Behavior.HtmlTableKeyboard.js,
  Source/BehaviorFilters/Behavior.HtmlTableLiveTreeKeyboard.js,
  Source/BehaviorFilters/Behavior.HtmlTableMultiSelectMenu.js,
  Source/BehaviorFilters/Behavior.HtmlTableRestore.js,
  Source/BehaviorFilters/Behavior.HtmlTableUpdate.js,
  Source/BehaviorFilters/Behavior.InputFilterHtmlTableZebra.js,
  Source/BehaviorFilters/Behavior.JFrameFormValidator.js,
  Source/BehaviorFilters/Behavior.MultiChecks.js,
  Source/BehaviorFilters/Behavior.PostEditor.js,
  Source/BehaviorFilters/Behavior.SelectWithOther.js,
  Source/BehaviorFilters/Behavior.SideBySideSelect.js,
  Source/BehaviorFilters/Behavior.SizeTo.js,
  Source/BehaviorFilters/Behavior.SplitViewPostFold.js,
  Source/BehaviorFilters/Behavior.SplitViewScroller.js,
  Source/BehaviorFilters/Behavior.SubmitOnChange.js,
  Source/BehaviorFilters/Behavior.Tabs.js,
  Source/BehaviorFilters/Behavior.Tips.js,
  Source/BehaviorFilters/Behavior.Timer.js,
  Source/UI/ART.SideBySideSelect.js,
  Source/UI/ContextMenu.js,
  Source/UI/FlashMessage.js,
  Source/UI/MultiChecks.js,
  Source/Utilities/Events.Relay.js,
]
version: Unknown
